chore!: split plan and apply logs (#76)
* Breaking Change!: Remove apply as output var
* Split plan logs if above limit
* Split apply logs if above limit
* Refactor - remove unneeded id's and make plan & apply as similar as possible
* Add status to Github Step Summary
* Plan and Apply logs saved as downloadable artefacts
* Icons, Icons everywhere! 🌈

---------

Co-authored-by: Glenn-Terjesen <Glenn-Terjesen@users.noreply.github.com>

diff --git a/.github/workflows/apply.yml b/.github/workflows/apply.yml
--- a/.github/workflows/apply.yml
+++ b/.github/workflows/apply.yml
@@ -34,9 +34,6 @@ on:
         type: number
         default: 60
     outputs:
-      apply-log:
-        description: "Terraform apply log"
-        value: ${{ jobs.terraform-apply.outputs.apply }}
       version:
         description: "Terraform version"
         value: ${{ jobs.terraform-apply.outputs.version }}
@@ -45,7 +42,6 @@ jobs:
   terraform-apply:
     runs-on: ubuntu-24.04
     outputs:
-      apply: ${{ steps.apply.outputs.apply }}
       version: ${{ steps.set-terraform-version.outputs.version }}
     timeout-minutes: ${{ inputs.timeout_minutes }}
     environment: ${{ inputs.environment }}
@@ -57,6 +53,10 @@ jobs:
       GHA_TERRAFORM_VERSION: ${{ inputs.version }}
       GHA_TERRAFORM_GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
       GHA_TERRAFORM_GCP_CLUSTER_NAME: ${{ inputs.gcp_cluster_name }}
+      GHA_TERRAFORM_PLAN_STATUS: 0
+      GHA_TERRAFORM_PLAN_SUMMARY: ""
+      GHA_TERRAFORM_APPLY_STATUS: 0
+      GHA_TERRAFORM_APPLY_SUMMARY: ""
       # ignore "context access might be invalid" warning
       GHA_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
       GHA_SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}
@@ -70,14 +70,13 @@ jobs:
       id-token: write
       pull-requests: write
     steps:
-      - id: set-workspace
-        name: Set Terraform Workspace
+      - name: Set Terraform Workspace
         shell: bash
         if: env.GHA_TERRAFORM_WORKSPACE == 'env'
         run: |
           echo "GHA_TERRAFORM_WORKSPACE=${GHA_TERRAFORM_ENVIRONMENT}" >> $GITHUB_ENV
-      - id: set-clustername
-        name: Set Cluster Name
+
+      - name: Set Cluster Name
         shell: bash
         if: inputs.cloud_provider == 'az'
         env:
@@ -88,10 +87,12 @@ jobs:
             exit 1
           fi
           echo "GHA_TERRAFORM_CLUSTER_NAME=${GHA_TERRAFORM_CLUSTER_NAME}" >> $GITHUB_ENV
-      - name: checkout
+
+      - name: Checkout
         uses: actions/checkout@v4
 
-      - uses: entur/gha-meta/.github/actions/cloud-auth@v1
+      - name: Authenticate with Cloud Provider
+        uses: entur/gha-meta/.github/actions/cloud-auth@v1
         with:
           environment: ${{ env.GHA_TERRAFORM_ENVIRONMENT }}
           cloud_provider: ${{ env.GHA_TERRAFORM_CLOUD_PROVIDER }}
@@ -101,7 +102,8 @@ jobs:
           azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
           azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
 
-      - uses: entur/gha-meta/.github/actions/k8s-auth@v1
+      - name: Authenticate with Kubernetes
+        uses: entur/gha-meta/.github/actions/k8s-auth@v1
         with:
           environment: ${{ env.GHA_TERRAFORM_ENVIRONMENT }}
           cloud_provider: ${{ env.GHA_TERRAFORM_CLOUD_PROVIDER }}
@@ -109,20 +111,20 @@ jobs:
           gcp_cluster_name: ${{ env.GHA_TERRAFORM_GCP_CLUSTER_NAME }}
           azure_cluster_resource_group: ${{ env.AZURE_CLUSTER_RESOURCE_GROUP }}
 
-      - name: "Terraform Version Action"
+      - name: Set Terraform Version
         id: set-terraform-version
         uses: entur/gha-terraform/.github/actions/terraform-version@v1
         with:
           directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
           version: ${{ env.GHA_TERRAFORM_VERSION }}
 
-      - uses: hashicorp/setup-terraform@v3
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: ${{ steps.set-terraform-version.outputs.version }}
           terraform_wrapper: false
 
       - name: Terraform Init
-        id: init
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
@@ -130,27 +132,195 @@ jobs:
           terraform init
 
       - name: Terraform Workspace
-        id: workspace
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
           terraform workspace select -or-create=true ${GHA_TERRAFORM_WORKSPACE}
 
-      - name: Terraform Apply
-        id: apply
+      - name: Terraform Plan
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
-          delimiter="$(openssl rand -hex 10)"
-          ENV=$(echo "${GHA_TERRAFORM_ENVIRONMENT}"| awk '{print toupper($0)}')
-          echo "apply<<${delimiter}" >> $GITHUB_OUTPUT
-          echo "## Terraform Apply $ENV" >> $GITHUB_OUTPUT
-          echo "The result of \`terraform apply\` in environment: \`$ENV\`" >> $GITHUB_OUTPUT
-          echo '```tf' >> $GITHUB_OUTPUT
-          terraform apply --auto-approve -var-file=env/${GHA_TERRAFORM_ENVIRONMENT}.tfvars -input=false -no-color >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "${delimiter}" >> $GITHUB_OUTPUT
+          set +e
+          # Run terraform plan and save the plan to a file, but also save any errors to a variable
+          { err=$(terraform plan -var-file=env/${GHA_TERRAFORM_ENVIRONMENT}.tfvars -detailed-exitcode -no-color -out tfplan 2>&1 >&3 3>&-); } 3>&1
+          echo "GHA_TERRAFORM_PLAN_STATUS=$?" >> $GITHUB_ENV
+          set -e
+          # Save the multiline error to the Summary, if empty/ok, it will be overwritten later
+          echo "GHA_TERRAFORM_PLAN_SUMMARY<<EOF" >> $GITHUB_ENV
+          echo "${err}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
 
-      - name: Terraform Apply Status Check
-        if: steps.apply.outcome == 'failure'
-        run: exit 1
+          # Save the plan output to a file so we can upload as a artifact
+          terraform show -no-color tfplan > tfplan.txt
+
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2
+        name: Terraform Apply
+        working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
+        shell: bash
+        run: |
+          set +e
+          # Apply the plan, but also save any errors to the file
+          terraform apply -no-color tfplan 2>&1|tee tfapply.txt
+          echo "GHA_TERRAFORM_APPLY_STATUS=${PIPESTATUS[0]}" >> $GITHUB_ENV
+          set -e
+
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2 && env.GHA_TERRAFORM_APPLY_STATUS == 0
+        name: Terraform Changes Detected
+        working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
+        shell: bash
+        run: |
+          # Create highlights of the changes
+          GHA_TERRAFORM_APPLY_SUMMARY=$(cat tfapply.txt |grep -E '(^[[:punct:]]|Apply complete)')
+          echo "GHA_TERRAFORM_APPLY_SUMMARY=${GHA_TERRAFORM_APPLY_SUMMARY}" >> $GITHUB_ENV
+          echo ":page_facing_up: ${GHA_TERRAFORM_APPLY_SUMMARY}" >> $GITHUB_STEP_SUMMARY
+
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2 && env.GHA_TERRAFORM_APPLY_STATUS == 0
+        name: Upload Plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: tfapply.txt
+          path: |
+            ${{ env.GHA_TERRAFORM_DIRECTORY }}/tfapply.txt
+            ${{ env.GHA_TERRAFORM_DIRECTORY }}/tfplan.txt
+          if-no-files-found: error
+
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2 && env.GHA_TERRAFORM_APPLY_STATUS == 0
+        name: Split apply output
+        working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
+        shell: bash
+        run: |
+          # Split the files on maxlen characters, but only on double newlines
+          cat > split.awk << EOF
+          BEGIN {
+            RS = "\n\n"
+            ORS = "\n\n"
+            maxlen = 55000
+            i = 1
+          }
+          {
+            reclen = length(\$0) + 2
+            l = n + reclen
+            if (l > maxlen) {
+                i++
+                n = 0
+            }
+            n += reclen
+            print \$0 > FILENAME"."i
+          }
+          EOF
+          # Split the files
+          awk -f split.awk tfapply.txt
+
+      - name: Delete previous apply comments for same environment
+        if: github.event_name == 'pull_request'
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number
+            });
+            const commentsFilter = `Terraform Apply ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()}`;
+            console.log(commentsFilter);
+
+            for (const comment of comments) {
+              if (comment.user.login === 'github-actions[bot]' && comment.body.includes(commentsFilter)) {
+              console.log(comment.body);
+              await github.rest.issues.deleteComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: comment.id
+              });
+              }
+            }
+
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2 && github.event_name == 'pull_request'
+        name: Terraform Apply Status
+        uses: actions/github-script@v7
+        with:
+          script: |
+            function filesort(x,y) {
+              x=parseInt(x.split('.').slice(-1));
+              y=parseInt(y.split('.').slice(-1));
+              return x<y ? -1 : x>y ? 1 : 0;
+            }
+            const artifactResponse = await github.rest.actions.listWorkflowRunArtifacts({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              run_id: context.runId
+            });
+            const artifact = artifactResponse.data.artifacts.find(a => a.name === 'tfapply.txt');
+            if (!artifact) {
+              throw new Error('Artifact not found');
+            }
+            const artifact_id = artifact.id;
+            const fs = require('fs')
+            const globber = await glob.create(`${process.env.GHA_TERRAFORM_DIRECTORY}/tfapply.txt.*`)
+            const files = await globber.glob()
+            files.sort(filesort)
+            const codeblockstart = '```tf\n'
+            const codeblockend = '\n```\n'
+            const downloadlink = `\n[Download Apply](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}/artifacts/${artifact_id})\n`;
+            let apply = '';
+            let n = 0;
+            let body = '';
+            let header = '';
+            let status = ':white_check_mark:';
+            if (process.env.GHA_TERRAFORM_APPLY_STATUS != 0) {
+              status = ':x:';
+            }
+            for (const file of files) {
+              apply = fs.readFileSync(file, 'utf8');
+              if (files.length > 1) {
+                n++
+                header = `## ${status} Terraform Apply ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()} - Part ${n}/${files.length}\n`;
+                if (n == 1) {
+                  body = `${header} ${codeblockstart} ${process.env.GHA_TERRAFORM_APPLY_SUMMARY} ${codeblockend} ${codeblockstart} ${apply} ${codeblockend} ${downloadlink}\n`;
+                } else {
+                  body = `${header} ${codeblockstart} ${apply} ${codeblockend}\n`;
+                }
+              }else{
+                header = `## ${status} Terraform Apply ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()}\n`;
+                body = `${header} ${codeblockstart} ${process.env.GHA_TERRAFORM_APPLY_SUMMARY} ${codeblockend} ${codeblockstart} ${apply} ${codeblockend} ${downloadlink}\n`;
+              }
+              await github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: body
+              })
+            }
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 0
+        name: Terraform Plan No Changes
+        shell: bash
+        run: |
+          GHA_TERRAFORM_PLAN_SUMMARY="## :heavy_check_mark: Terraform Apply - Your infrastructure matches the configuration"
+          echo "${GHA_TERRAFORM_PLAN_SUMMARY}" >> $GITHUB_STEP_SUMMARY
+
+      - if: github.event_name == 'pull_request' && env.GHA_TERRAFORM_PLAN_STATUS == 1
+        name: Terraform Plan Status Check Comment
+        uses: actions/github-script@v7
+        with:
+          script: |
+            await github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `## :x: Terraform Plan ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()}\n\nTerraform plan failed. \n\n${process.env.GHA_TERRAFORM_PLAN_SUMMARY}`
+            })
+      - if: (env.GHA_TERRAFORM_PLAN_STATUS != 0 && env.GHA_TERRAFORM_PLAN_STATUS != 2) || env.GHA_TERRAFORM_APPLY_STATUS != 0
+        name: Terraform Apply Status Check
+        working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
+        shell: bash
+        run: |
+          if [ -f tfapply.txt ]; then
+            # get last 20 lines of tfapply.txt to show in summary
+            GHA_TERRAFORM_APPLY_SUMMARY=$(tail -n 20 tfapply.txt)
+          else
+            GHA_TERRAFORM_APPLY_SUMMARY="No tfapply.txt file found"
+          fi
+          GHA_TERRAFORM_APPLY_SUMMARY="## :x: Terraform Apply failed\n\n${GHA_TERRAFORM_PLAN_SUMMARY}, ${GHA_TERRAFORM_APPLY_SUMMARY}"
+          echo "${GHA_TERRAFORM_APPLY_SUMMARY}" >> $GITHUB_STEP_SUMMARY
+          exit 99
diff --git a/.github/workflows/plan.yml b/.github/workflows/plan.yml
--- a/.github/workflows/plan.yml
+++ b/.github/workflows/plan.yml
@@ -51,8 +51,8 @@ jobs:
       GHA_TERRAFORM_VERSION: ${{ inputs.version }}
       GHA_TERRAFORM_GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
       GHA_TERRAFORM_GCP_CLUSTER_NAME: ${{ inputs.gcp_cluster_name }}
-      GHA_TERRAFORM_STATUS: ""
-      GHA_TERRAFORM_SUMMARY: ""
+      GHA_TERRAFORM_PLAN_STATUS: 0
+      GHA_TERRAFORM_PLAN_SUMMARY: ""
       # ignore "context access might be invalid" warning
       WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
       SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}
@@ -68,17 +68,17 @@ jobs:
     outputs:
       version: ${{ steps.set-terraform-version.outputs.version }}
     steps:
-      - id: set-workspace
+      - if: env.GHA_TERRAFORM_WORKSPACE == 'env'
+        name: Set Terraform Workspace Variable
         shell: bash
-        if: env.GHA_TERRAFORM_WORKSPACE == 'env'
         run: |
           echo "GHA_TERRAFORM_WORKSPACE=${GHA_TERRAFORM_ENVIRONMENT}" >> $GITHUB_ENV
 
-      - name: checkout
+      - name: Checkout
         uses: actions/checkout@v4
 
-      - uses: entur/gha-meta/.github/actions/cloud-auth@v1
-        name: Authenticate
+      - name: Authenticate with Cloud Provider
+        uses: entur/gha-meta/.github/actions/cloud-auth@v1
         with:
           environment: ${{ env.GHA_TERRAFORM_ENVIRONMENT }}
           cloud_provider: ${{ env.GHA_TERRAFORM_CLOUD_PROVIDER }}
@@ -88,7 +88,8 @@ jobs:
           azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
           azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
 
-      - uses: entur/gha-meta/.github/actions/k8s-auth@v1
+      - name: Authenticate with Kubernetes
+        uses: entur/gha-meta/.github/actions/k8s-auth@v1
         with:
           environment: ${{ env.GHA_TERRAFORM_ENVIRONMENT }}
           cloud_provider: ${{ env.GHA_TERRAFORM_CLOUD_PROVIDER }}
@@ -96,20 +97,20 @@ jobs:
           gcp_cluster_name: ${{ env.GHA_TERRAFORM_GCP_CLUSTER_NAME }}
           azure_cluster_resource_group: ${{ env.AZURE_CLUSTER_RESOURCE_GROUP }}
 
-      - name: "Terraform Version Action"
+      - name: Set Terraform Version
         id: set-terraform-version
         uses: entur/gha-terraform/.github/actions/terraform-version@v1
         with:
           directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
           version: ${{ env.GHA_TERRAFORM_VERSION }}
 
-      - uses: hashicorp/setup-terraform@v3
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: ${{ steps.set-terraform-version.outputs.version }}
           terraform_wrapper: false
 
       - name: Terraform Init
-        id: init
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
@@ -117,35 +118,43 @@ jobs:
           terraform init
 
       - name: Terraform Workspace
-        id: workspace
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
           terraform workspace select -or-create=true ${GHA_TERRAFORM_WORKSPACE}
 
       - name: Terraform Plan
-        id: plan
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
           set +e
-          terraform plan -var-file=env/${GHA_TERRAFORM_ENVIRONMENT}.tfvars -detailed-exitcode -out tfplan
-          echo "GHA_TERRAFORM_STATUS=$?" >> $GITHUB_ENV
+          # Run terraform plan and save the plan to a file, but also save any errors to a variable
+          { err=$(terraform plan -var-file=env/${GHA_TERRAFORM_ENVIRONMENT}.tfvars -detailed-exitcode -no-color -out tfplan 2>&1 >&3 3>&-); } 3>&1
+          echo "GHA_TERRAFORM_PLAN_STATUS=$?" >> $GITHUB_ENV
           set -e
+          # Save the multiline error to the Summary, if empty/ok, it will be overwritten later
+          echo "GHA_TERRAFORM_PLAN_SUMMARY<<EOF" >> $GITHUB_ENV
+          echo "${err}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+          # Print the error to the log for debugging
+          echo "${err}"
 
-      - if: env.GHA_TERRAFORM_STATUS == 2
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2
         name: Terraform Changes Detected
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
           # Save the plan output to a file so we can upload as a artifact and add a download link to the PR comment
-          terraform show -no-color tfplan > tfplan.tf
+          terraform show -no-color tfplan > tfplan.txt
           # Create highlights of the changes
-          GHA_TERRAFORM_SUMMARY=$(terraform show -no-color tfplan |grep -E '(^[[:punct:]]|Plan)')
-          echo "GHA_TERRAFORM_SUMMARY=${GHA_TERRAFORM_SUMMARY}" >> $GITHUB_ENV
+          GHA_TERRAFORM_PLAN_SUMMARY=$(terraform show -no-color tfplan |grep -E '(^[[:punct:]]|Plan)')
+          echo "GHA_TERRAFORM_PLAN_SUMMARY<<EOF" >> $GITHUB_ENV
+          echo "${GHA_TERRAFORM_PLAN_SUMMARY}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+          echo ":page_facing_up: ${GHA_TERRAFORM_PLAN_SUMMARY}" >> $GITHUB_STEP_SUMMARY
 
-      - if: env.GHA_TERRAFORM_STATUS == 2
-        name: Split plan and create summary
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2
+        name: Split plan
         working-directory: ${{ env.GHA_TERRAFORM_DIRECTORY }}
         shell: bash
         run: |
@@ -169,17 +178,10 @@ jobs:
           }
           EOF
           # Split the files
-          awk -f split.awk tfplan.tf
+          awk -f split.awk tfplan.txt
 
-      - if: env.GHA_TERRAFORM_STATUS != 0 && env.GHA_TERRAFORM_STATUS != 2
-        name: Terraform Plan Status Check
-        shell: bash
-        run: |
-          echo GHA_TERRAFORM_SUMMARY="Plan failed" >> $GITHUB_ENV
-          exit 99
-
-      - name: Delete previous plan comments for same environment
-        if: github.event_name == 'pull_request'
+      - if: github.event_name == 'pull_request'
+        name: Delete previous plan comments for same environment
         uses: actions/github-script@v7
         with:
           script: |
@@ -202,16 +204,15 @@ jobs:
               }
             }
 
-      - name: Upload Plan
-        id: upload
-        if: env.GHA_TERRAFORM_STATUS == 2
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2
+        name: Upload Plan
         uses: actions/upload-artifact@v4
         with:
-          name: tfplan.tf
-          path: ${{ env.GHA_TERRAFORM_DIRECTORY }}/tfplan.tf
+          name: tfplan.txt
+          path: ${{ env.GHA_TERRAFORM_DIRECTORY }}/tfplan.txt
           if-no-files-found: error
 
-      - if: env.GHA_TERRAFORM_STATUS == 2 && github.event_name == 'pull_request'
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 2 && github.event_name == 'pull_request'
         name: Terraform Plan Status
         uses: actions/github-script@v7
         with:
@@ -226,13 +227,13 @@ jobs:
               repo: context.repo.repo,
               run_id: context.runId
             });
-            const artifact = artifactResponse.data.artifacts.find(a => a.name === 'tfplan.tf');
+            const artifact = artifactResponse.data.artifacts.find(a => a.name === 'tfplan.txt');
             if (!artifact) {
               throw new Error('Artifact not found');
             }
             const artifact_id = artifact.id;
             const fs = require('fs')
-            const globber = await glob.create(`${process.env.GHA_TERRAFORM_DIRECTORY}/tfplan.tf.*`)
+            const globber = await glob.create(`${process.env.GHA_TERRAFORM_DIRECTORY}/tfplan.txt.*`)
             const files = await globber.glob()
             files.sort(filesort)
             const codeblockstart = '```tf\n'
@@ -246,15 +247,15 @@ jobs:
               plan = fs.readFileSync(file, 'utf8');
               if (files.length > 1) {
                 n++
-                header = `## Terraform Plan ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()} - Part ${n}/${files.length}\n`;
+                header = `## :page_facing_up: Terraform Plan ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()} - Part ${n}/${files.length}\n`;
                 if (n == 1) {
-                  body = `${header} ${codeblockstart} ${process.env.GHA_TERRAFORM_SUMMARY} ${codeblockend} ${codeblockstart} ${plan} ${codeblockend} ${downloadlink}\n`;
+                  body = `${header} ${codeblockstart} ${process.env.GHA_TERRAFORM_PLAN_SUMMARY} ${codeblockend} ${codeblockstart} ${plan} ${codeblockend} ${downloadlink}\n`;
                 } else {
                   body = `${header} ${codeblockstart} ${plan} ${codeblockend}\n`;
                 }
               }else{
-                header = `## Terraform Plan ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()}\n`;
-                body = `${header} ${codeblockstart} ${process.env.GHA_TERRAFORM_SUMMARY} ${codeblockend} ${codeblockstart} ${plan} ${codeblockend} ${downloadlink}\n`;
+                header = `## :page_facing_up: Terraform Plan ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()}\n`;
+                body = `${header} ${codeblockstart} ${process.env.GHA_TERRAFORM_PLAN_SUMMARY} ${codeblockend} ${codeblockstart} ${plan} ${codeblockend} ${downloadlink}\n`;
               }
               await github.rest.issues.createComment({
                 issue_number: context.issue.number,
@@ -263,3 +264,29 @@ jobs:
                 body: body
               })
             }
+      - if: env.GHA_TERRAFORM_PLAN_STATUS == 0
+        name: Terraform Plan No Changes
+        shell: bash
+        run: |
+          GHA_TERRAFORM_PLAN_SUMMARY="## :heavy_check_mark: Terraform Plan - Your infrastructure matches the configuration"
+          echo "${GHA_TERRAFORM_PLAN_SUMMARY}" >> $GITHUB_STEP_SUMMARY
+
+      - if: github.event_name == 'pull_request' && env.GHA_TERRAFORM_PLAN_STATUS != 0 && env.GHA_TERRAFORM_PLAN_STATUS != 2
+        name: Terraform Plan Status Check Comment
+        uses: actions/github-script@v7
+        with:
+          script: |
+            await github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `## :x: Terraform Plan ${process.env.GHA_TERRAFORM_ENVIRONMENT.toString().toUpperCase()}\n\nTerraform plan failed. \n\n${process.env.GHA_TERRAFORM_PLAN_SUMMARY}`
+            })
+
+      - if: env.GHA_TERRAFORM_PLAN_STATUS != 0 && env.GHA_TERRAFORM_PLAN_STATUS != 2
+        name: Terraform Plan Status Check
+        shell: bash
+        run: |
+          GHA_TERRAFORM_PLAN_SUMMARY="## :x: Terraform Plan failed\n\n${GHA_TERRAFORM_PLAN_SUMMARY}"
+          echo "${GHA_TERRAFORM_PLAN_SUMMARY}" >> $GITHUB_STEP_SUMMARY
+          exit 99
