chore: refactor

diff --git a/.github/workflows/plan.yml b/.github/workflows/plan.yml
--- a/.github/workflows/plan.yml
+++ b/.github/workflows/plan.yml
@@ -117,8 +117,8 @@ jobs:
         shell: bash
         run: |
           delimiter="$(openssl rand -hex 10)"
-          # allow exit code > 0
-          set -e
+          # allow exit code > 0 to print failure in comment
+          set +e
           terraform plan -var-file=env/${GHA_TERRAFORM_ENVIRONMENT}.tfvars -detailed-exitcode -no-color -out tfplan
           TFSTATUS=$?
           set -e
@@ -159,4 +159,5 @@ jobs:
             })
       - name: Terraform Plan Status Check
         if: steps.plan.outcome == 'failure' || env.GHA_TERRAFORM_STATUS == 'Error'
-        run: exit 1
+        run: |
+          exit 1
